version: '3.8'
services:
  payall-gateway-service:
    container_name: payall-gateway-service
    image: asyst-payall-gateway:latest
    restart: always
    ports:
      - "7090:7090"
    networks:
      - eureka-network
    # depends_on:
    #   - payall-serveur-decouverte-service

networks:
  eureka-network:
    external: true
