# version: '3.8'
services:
  payall-gateway-service:
    container_name: payall-gateway-service
    image: asyst-payall-gateway:latest
    restart: always
    build: .
    ports:
      - "7090:7090"
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://payall-serveur-decouverte-service:8761/eureka
      
    # networks:
    #   - eureka-network
    # depends_on:
    #   - payall-serveur-decouverte-service

networks:
  eureka-network:
    external: true
